imports:
    - { resource: services.yml }

framework:
    secret: %secret%
    router:
        resource:            "%kernel.root_dir%/config/routing_%kernel.environment%.yml"
        strict_requirements: %kernel.debug%
    templating:
        engines: ['twig']
    session:
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    profiler:
        enabled: %kernel.debug%

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: %monolog_action_level%
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console